metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.99.110, mac: '18:60:24:e4:28:c7', disk: nvme0n1, network_interface: enp1s0}
        metal1: {ansible_host: 192.168.99.111, mac: '18:60:24:e5:3a:0c', disk: nvme0n1, network_interface: enp1s0}
        metal2: {ansible_host: 192.168.99.112, mac: '18:60:24:e6:3c:91', disk: nvme0n1, network_interface: enp1s0}
    workers:
      hosts:
        {}
        # metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f5:69', disk: sda, network_interface: eno1}

